# Generated by Django 3.2.7 on 2021-10-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_alter_messagerecipient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerecipient',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
