# Generated by Django 3.2.7 on 2021-10-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_messagerecipient_archive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-timestamp',)},
        ),
    ]
